name: fresh_mart
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animated_splash_screen: ^1.2.0
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  buttons_tabbar: ^1.3.6
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  eva_icons_flutter: ^3.1.0
  favorite_button: ^0.0.4
  file_picker: ^4.6.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  form_field_validator: ^1.1.0
  geolocator: ^9.0.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl_phone_field: ^3.1.0
  lint: ^1.8.2
  loading_overlay: ^0.3.0
  lottie: ^1.3.0
  open_street_map_search_and_pick: ^0.0.9
  provider: ^6.0.3
  regexpattern: ^2.0.1
  shared_preferences: ^2.0.15
  skeleton_loader: ^2.0.0+4
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/animations/
    - assets/images/
    - imageitems/
    - imageitems/promotion/
  fonts:
    - family: Lobster-Regular
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: SquarePeg-Regular
      fonts:
        - asset: assets/fonts/SquarePeg-Regular.ttf
    - family: Fascinate-Regular
      fonts:
        - asset: assets/fonts/Fascinate-Regular.ttf
    - family: TitanOne-Regular
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf
    - family: LibreBaskerville-Regular
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
